### ISSUE TITLE
Error when running homebridge

### ISSUE THREAD

**Issue by benquan** [KraigM/homebridge-gpio-garagedoor#5]
I downloaded the plugin and modified the config.json file but I am getting this error when running homebridge: any help?

```
[10/27/2016, 7:24:58 AM] Plugin /usr/lib/nodejs does not have a package name that begins with 'homebridge-'.
[10/27/2016, 7:24:59 AM] Loaded plugin: homebridge-gpio-garagedoor
[10/27/2016, 7:24:59 AM] Registering accessory 'homebridge-gpio-garagedoor.GPIOGarageDoor'
[10/27/2016, 7:24:59 AM] ---
[10/27/2016, 7:24:59 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/27/2016, 7:24:59 AM] ---
[10/27/2016, 7:24:59 AM] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:104
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:104:11)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:281:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:77:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:382:7)
    at startup (bootstrap_node.js:137:9)
    at bootstrap_node.js:497:3

```

**Comment by DanielGalle** [comment]
Same error for me :(

**Comment by lexxnsk** [comment]
Same error. Any solutions?

**Comment by Downlosc** [comment]
did you find any solutions?

**Comment by toshibochan** [comment]
Post your config!
